@startuml
skinparam componentStyle uml2

package eadlib #DDDDDD{
    [wrapper::SQLite]
    [WeightedGraph<T>]
}

package sbp #DDDDDD {
    [io::FastaParser]
    [io::Database]
    [io::DotExport]
    [graph::GraphConstructor]
    [graph::GraphIndexer]
    [algo::GraphCompressor]
    [algo::SB_Driver]
}

database "SQLite\nDB" as DB
file ".FASTA\nreads\nfile" as FASTA
file ".Dot\nformat\ngraph\nfile" as DOT
file "Benchmark\nResults\nfile" as BENCHMARK

FASTA -down-> [io::FastaParser]
[io::FastaParser] -down-> [graph::GraphConstructor]  : "Sequencer reads"
[graph::GraphConstructor] -down-> [algo::GraphCompressor] : [eadlib::WeightedGraph<std::string>]
[algo::GraphCompressor] -down-> [graph::GraphIndexer] : [eadlib::WeightedGraph<std::string>]
[graph::GraphIndexer] -down-> [io::Database]
[graph::GraphIndexer] -> [algo::SB_Driver] : eadlib::WeightedGraph<size_t>
[io::Database] -down-> [algo::SB_Driver]
[io::Database] -down-* [wrapper::SQLite]
[io::Database] -left-> [io::DotExport] : eadlib::WeightedGraph<std::string>\nor eadlib::WeightedGraph<size_t>
[wrapper::SQLite] -down-> DB
[io::DotExport] -down-> DOT
[algo::SB_Driver] -right-> BENCHMARK
[algo::SB_Driver] -down-> [io::Database]

@enduml